
"""
Stream Analytics Dashboard
Uses real ATP historical match stream results.
"""

import json
from pathlib import Path

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[1]

RESULTS_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "real_atp_stream_results.json"
)


def load_stream_results():
    """Load results generated by the real ATP stream processor."""

    if not RESULTS_PATH.exists():
        return None

    with open(RESULTS_PATH, "r", encoding="utf-8") as file:
        return json.load(file)


def render_stream_analytics():
    """Render the Stream Analytics page."""

    st.title("🎾 Stream Analytics")
    st.caption(
        "Sequential stream mining of historical ATP match participation events"
    )

    results = load_stream_results()

    if results is None:
        st.error(
            "Stream results not found. Run the stream processor first:\n\n"
            "python -m src.stream_mining.tennis_match_stream"
        )
        return

    stream_metrics = results.get("stream_metrics", {})
    additional_metrics = results.get("additional_metrics", {})

    # ---------------------------------------------------------
    # Dataset information
    # ---------------------------------------------------------

    st.info(
        "This dashboard uses historical ATP match records converted "
        "into sequential winner and loser participation events. "
        "It is not a live point-by-point tennis feed."
    )

    # ---------------------------------------------------------
    # KPI cards
    # ---------------------------------------------------------

    total_events = (
        results.get("total_source_events")
        or stream_metrics.get("total_events", 0)
    )

    exact_players = stream_metrics.get("exact_distinct_players", 0)
    estimated_players = stream_metrics.get(
        "estimated_distinct_players", 0
    )
    exact_matches = stream_metrics.get("exact_distinct_matches", 0)
    duplicate_events = stream_metrics.get("duplicate_events", 0)
    duplicate_rate = stream_metrics.get("duplicate_rate", 0)

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Total Stream Events", f"{total_events:,}")

    with col2:
        st.metric("Exact Distinct Players", f"{exact_players:,}")

    with col3:
        st.metric(
            "Estimated Distinct Players",
            f"{estimated_players:,}",
        )

    with col4:
        st.metric("Distinct Matches", f"{exact_matches:,}")

    st.divider()

    # ---------------------------------------------------------
    # Duplicate detection
    # ---------------------------------------------------------

    st.subheader("🔎 Duplicate Detection")

    duplicate_col1, duplicate_col2 = st.columns(2)

    with duplicate_col1:
        st.metric(
            "Duplicate Events",
            f"{duplicate_events:,}",
        )

    with duplicate_col2:
        st.metric(
            "Duplicate Rate",
            f"{duplicate_rate * 100:.2f}%",
        )

    st.caption(
        "The Bloom Filter is used for duplicate-event detection. "
        "A zero duplicate count is valid when the source event IDs "
        "are unique."
    )

    st.divider()

    # ---------------------------------------------------------
    # Event type distribution
    # ---------------------------------------------------------

    st.subheader("📊 Event Type Distribution")

    event_type_counts = additional_metrics.get(
        "event_type_counts",
        {},
    )

    if event_type_counts:
        event_type_df = pd.DataFrame(
            {
                "Event Type": list(event_type_counts.keys()),
                "Count": list(event_type_counts.values()),
            }
        )

        st.bar_chart(
            event_type_df.set_index("Event Type")
        )

        st.dataframe(
            event_type_df,
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.warning("No event type data available.")

    st.divider()

    # ---------------------------------------------------------
    # Surface distribution
    # ---------------------------------------------------------

    st.subheader("🎾 Surface Distribution")

    surface_counts = additional_metrics.get(
        "surface_event_counts",
        {},
    )

    if surface_counts:
        surface_df = pd.DataFrame(
            {
                "Surface": list(surface_counts.keys()),
                "Events": list(surface_counts.values()),
            }
        )

        surface_col1, surface_col2 = st.columns(2)

        with surface_col1:
            st.bar_chart(
                surface_df.set_index("Surface")
            )

        with surface_col2:
            st.dataframe(
                surface_df,
                use_container_width=True,
                hide_index=True,
            )
    else:
        st.warning("No surface data available.")

    st.divider()

    # ---------------------------------------------------------
    # Top players by participation
    # ---------------------------------------------------------

    st.subheader("🏆 Top Players by Match Participation")

    top_players = additional_metrics.get(
        "top_players_by_match_participation",
        [],
    )

    if top_players:
        player_df = pd.DataFrame(top_players)

        player_df = player_df.rename(
            columns={
                "player": "Player",
                "matches": "Matches",
            }
        )

        player_col1, player_col2 = st.columns(2)

        with player_col1:
            st.bar_chart(
                player_df.set_index("Player")["Matches"]
            )

        with player_col2:
            st.dataframe(
                player_df,
                use_container_width=True,
                hide_index=True,
            )
    else:
        st.warning("No player participation data available.")

    st.divider()

    # ---------------------------------------------------------
    # Top tournaments
    # ---------------------------------------------------------

    st.subheader("🏟️ Top Tournaments by Stream Events")

    top_tournaments = additional_metrics.get(
        "top_tournaments_by_events",
        [],
    )

    if top_tournaments:
        tournament_df = pd.DataFrame(top_tournaments)

        tournament_df = tournament_df.rename(
            columns={
                "tournament": "Tournament",
                "events": "Events",
            }
        )

        st.bar_chart(
            tournament_df.set_index("Tournament")["Events"]
        )

        st.dataframe(
            tournament_df,
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.warning("No tournament data available.")

    st.divider()

    # ---------------------------------------------------------
    # Sliding window
    # ---------------------------------------------------------

    st.subheader("🪟 Sliding Window Analysis")

    window_size = stream_metrics.get(
        "configured_window_size",
        0,
    )

    active_window_size = stream_metrics.get(
        "active_window_size",
        0,
    )

    window_col1, window_col2 = st.columns(2)

    with window_col1:
        st.metric(
            "Configured Window Size",
            f"{window_size:,}",
        )

    with window_col2:
        st.metric(
            "Active Window Events",
            f"{active_window_size:,}",
        )

    st.caption(
        "The sliding window retains the most recent events "
        "according to the configured window size."
    )

    st.divider()

    # ---------------------------------------------------------
    # Stream timeline
    # ---------------------------------------------------------

    st.subheader("⏱️ Stream Timeline")

    first_timestamp = stream_metrics.get(
        "first_timestamp",
        "Unavailable",
    )

    last_timestamp = stream_metrics.get(
        "last_timestamp",
        "Unavailable",
    )

    timeline_col1, timeline_col2 = st.columns(2)

    with timeline_col1:
        st.write("**First Event**")
        st.code(str(first_timestamp))

    with timeline_col2:
        st.write("**Last Event**")
        st.code(str(last_timestamp))

    # ---------------------------------------------------------
    # Raw metrics
    # ---------------------------------------------------------

    with st.expander("View Raw Stream Metrics"):
        st.json(stream_metrics)

    with st.expander("View Complete Stream Results"):
        st.json(results)

if __name__ == "__main__":
    render_stream_analytics()